local P = {
  require 'plugins.vimtex',
  require 'plugins.elixir',
  require 'plugins.go',
  require 'plugins.vim-visual-multi',
  require 'plugins.nvim-dap-python',
  require 'plugins.toggleterm',
  require 'plugins.comment',
  require 'plugins.nvim-lspconfig',
  require 'plugins.conform',
  require 'plugins.nvim-cmp',
  require 'plugins.gitsigns',
  require 'plugins.telescope',
  require 'plugins.which-key',
  require 'plugins.mini',
  require 'plugins.tokyonight',
  require 'plugins.nvim-treesitter',
  require 'plugins.vim-sleuth',
  require 'plugins.nvim-autopairs',
  require 'plugins.nvim-tree',
  require 'plugins.nvim-surround',
  require 'plugins.nvim-ts-autotag',
}

return P
